spring.application.name=demo
nts.api.key=2fbe0909d103f55fb2008e0cd7f5caeabd56fa1be3f8f69f3e3a740e0fa75797
dart.api.key=39952312fc731552972818ce29208b7fea2f4ebb

# restTemplate : HTTP 요청을 보내고 응답을 받을 수 있게 해주는 객체
# Value: application.properties 파일에서 값을 읽어와 변수에 자동으로 할당해주는 기능

# Kakao REST_API Key
kakao.api.key=ab800c313ceb4cf4466175889f09e9e8
